// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPnLrIzf8wJCEMuuoCcqx4OUMtAgLoUiY',
    appId: '1:180104404017:web:33836ef31207bfa63b4910',
    messagingSenderId: '180104404017',
    projectId: 'space-metro-by-obotu',
    authDomain: 'space-metro-by-obotu.firebaseapp.com',
    storageBucket: 'space-metro-by-obotu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARVInVauel1Ja3q9K4DHncVS2zqH537TI',
    appId: '1:180104404017:android:095799866049cab63b4910',
    messagingSenderId: '180104404017',
    projectId: 'space-metro-by-obotu',
    storageBucket: 'space-metro-by-obotu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHK4KTogqrvDxv1A-OgfhPKwDIIVLOzn8',
    appId: '1:180104404017:ios:9c73329919081bce3b4910',
    messagingSenderId: '180104404017',
    projectId: 'space-metro-by-obotu',
    storageBucket: 'space-metro-by-obotu.appspot.com',
    iosBundleId: 'com.example.spaceMetro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHK4KTogqrvDxv1A-OgfhPKwDIIVLOzn8',
    appId: '1:180104404017:ios:209b5d8521ea6db53b4910',
    messagingSenderId: '180104404017',
    projectId: 'space-metro-by-obotu',
    storageBucket: 'space-metro-by-obotu.appspot.com',
    iosBundleId: 'com.example.spaceMetro.RunnerTests',
  );
}
